#pragma once

#define IVX_MOUSE_BUTTON_1         0
#define IVX_MOUSE_BUTTON_2         1
#define IVX_MOUSE_BUTTON_3         2
#define IVX_MOUSE_BUTTON_4         3
#define IVX_MOUSE_BUTTON_5         4
#define IVX_MOUSE_BUTTON_6         5
#define IVX_MOUSE_BUTTON_7         6
#define IVX_MOUSE_BUTTON_8         7
#define IVX_MOUSE_BUTTON_LAST      IVX_MOUSE_BUTTON_8
#define IVX_MOUSE_BUTTON_LEFT      IVX_MOUSE_BUTTON_1
#define IVX_MOUSE_BUTTON_RIGHT     IVX_MOUSE_BUTTON_2
#define IVX_MOUSE_BUTTON_MIDDLE    IVX_MOUSE_BUTTON_3